name: Run tests and code checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  TESTING: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - name: Webhook
      uses: joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        headers: '{"repository": "joelwmale/webhook-action"}'
        body: '{"event": "actions", "status": "passsed"}'
