name: Run tests and code checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  TESTING: true
  PR_NUMBER: ${{ githubevent.number }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install libvirt-dev
        python -m pip install --upgrade pip
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  webhook:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Webhook
        uses: joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"repository": "joelwmale/webhook-action"}'
          body: '{"platform": "windows","event": "actions", "status": "passsed" , 'val': ${{PR_NUMBER}}}'
